### model
model_name_or_path: /data2/xucaijun/Qwen/Qwen2.5-1.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ds_z3_config.json

### dataset
dataset: bishe_test
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/MATH-Qwen2.5-Math-1.5B/full/sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
